//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkStoreManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CTHDs = new HashSet<CTHD>();
            this.CTPNs = new HashSet<CTPN>();
        }
    
        public string MASP { get; set; }
        public string TENSP { get; set; }
        public DateTime NSX { get; set; }
        public DateTime HSD { get; set; }
        public int KLG { get; set; }
        public string DVT { get; set; }
        public string MOTA { get; set; }
        public string XUATXU { get; set; }
        public string MALOAISP { get; set; }
        public decimal GIABAN { get; set; }
        public int SL { get; set; }
        public string MANCC { get; set; }
        private string _HINHSP;
        public string HINHSP
        {
            get
            {
                if (string.IsNullOrEmpty(_HINHSP))
                {
                    return Const._localLink + @"Resource\ImgProducts\ava1.jpg";
                }
                else if (_HINHSP.Contains(Const._localLink))
                {
                    return _HINHSP;
                }
                else
                {
                    return Const._localLink + _HINHSP;
                }
            }
            set { _HINHSP = value; }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPN> CTPNs { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
